services:
  postgres:
    image: postgres:16
    container_name: genaulingua_db
    environment:
      POSTGRES_USER: genau_user
      POSTGRES_PASSWORD: AA212121lodkZZ
      POSTGRES_DB: genaulingua_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: genaulingua_app
    depends_on:
      - postgres
    env_file:
      - .env
    command: >
      sh -c "
      echo 'Waiting for postgres...' &&
      sleep 5 &&
      alembic upgrade head &&
      python app/main.py
      "
    volumes:
      - .:/app

volumes:
  postgres_data:
