services:
  postgres:
    image: postgres:16
    container_name: genaulingua_db
    environment:
      POSTGRES_USER: genau_user
      POSTGRES_PASSWORD: genau_password
      POSTGRES_DB: genaulingua_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: genaulingua_app
    command: python -m app.main
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
